// <auto-generated />
using System;
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20241112025945_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Exercises", b =>
                {
                    b.Property<string>("ExerciseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("ExerciseID");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseID = "bench",
                            Name = "Bench",
                            Reps = 12,
                            Weight = 100
                        },
                        new
                        {
                            ExerciseID = "squat",
                            Name = "Squat",
                            Reps = 8,
                            Weight = 225
                        },
                        new
                        {
                            ExerciseID = "deadlift",
                            Name = "Deadlift",
                            Reps = 6,
                            Weight = 315
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("BodyWeight")
                        .HasColumnType("int");

                    b.Property<int>("P4PStrength")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            BodyWeight = 220,
                            P4PStrength = 50,
                            Password = "Test1",
                            Premium = false,
                            Username = "tate.padilla"
                        },
                        new
                        {
                            UserID = 2,
                            BodyWeight = 190,
                            P4PStrength = 50,
                            Password = "Test2",
                            Premium = false,
                            Username = "tommy.wells"
                        },
                        new
                        {
                            UserID = 3,
                            BodyWeight = 190,
                            P4PStrength = 50,
                            Password = "Test3",
                            Premium = false,
                            Username = "caden.heidebrink"
                        });
                });

            modelBuilder.Entity("UserExercises", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserID", "ExerciseID");

                    b.HasIndex("ExerciseID");

                    b.ToTable("UserExercises", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            ExerciseID = "bench"
                        },
                        new
                        {
                            UserID = 2,
                            ExerciseID = "squat"
                        },
                        new
                        {
                            UserID = 3,
                            ExerciseID = "deadlift"
                        });
                });

            modelBuilder.Entity("UserExercises", b =>
                {
                    b.HasOne("FinalProject.Models.Exercises", null)
                        .WithMany()
                        .HasForeignKey("ExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
