// <auto-generated />
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20241206010705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseUser", b =>
                {
                    b.Property<int>("ExercisesExerciseID")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserID")
                        .HasColumnType("int");

                    b.HasKey("ExercisesExerciseID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("ExerciseUser");

                    b.HasData(
                        new
                        {
                            ExercisesExerciseID = 1,
                            UsersUserID = 1
                        },
                        new
                        {
                            ExercisesExerciseID = 2,
                            UsersUserID = 2
                        },
                        new
                        {
                            ExercisesExerciseID = 3,
                            UsersUserID = 3
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("ExerciseID");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseID = 1,
                            Name = "Bench",
                            Reps = 12,
                            Weight = 100
                        },
                        new
                        {
                            ExerciseID = 2,
                            Name = "Squat",
                            Reps = 8,
                            Weight = 225
                        },
                        new
                        {
                            ExerciseID = 3,
                            Name = "Deadlift",
                            Reps = 6,
                            Weight = 315
                        });
                });

            modelBuilder.Entity("FinalProject.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int?>("BodyWeight")
                        .HasColumnType("int");

                    b.Property<int?>("P4PStrength")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            BodyWeight = 220,
                            P4PStrength = 50,
                            Password = "Test1",
                            Premium = true,
                            Username = "tate.padilla"
                        },
                        new
                        {
                            UserID = 2,
                            BodyWeight = 190,
                            P4PStrength = 50,
                            Password = "Test2",
                            Premium = false,
                            Username = "tommy.wells"
                        },
                        new
                        {
                            UserID = 3,
                            BodyWeight = 190,
                            P4PStrength = 50,
                            Password = "Test3",
                            Premium = false,
                            Username = "caden.heidebrink"
                        });
                });

            modelBuilder.Entity("ExerciseUser", b =>
                {
                    b.HasOne("FinalProject.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
